export const CONSULTORES = [
  'ALDO',
  'ANE KARYNE',
  'ARÃO',
  'ATAYSE',
  'BEATRIZ',
  'BRUNA',
  'C NOGUEIRA',
  'CASSIA',
  'CLAUDIONOR',
  'CLERISTON',
  'DAIANE',
  'DORA',
  'EDILANIA',
  'EDILENE',
  'EMERSON',
  'ERICO',
  'FABIO',
  'FABIO RIBEIRO',
  'FABIO SANTANA',
  'FELIPE',
  'FERNANDO',
  'GABRIELA',
  'GENIVAL',
  'HAROLDO',
  'HEBERT',
  'ILANIA',
  'JANAINA',
  'JOAO PEDRO',
  'JURANDI',
  'KARLA',
  'KELLYSON',
  'LUCAS',
  'LUCIANA',
  'MARCELO',
  'MARCOS',
  'MILENA',
  'MONALISA',
  'NERLON',
  'NIZAN',
  'PALOMA',
  'PEREIRA',
  'REGIONAL GO',
  'RICARDO',
  'RONALD',
  'RONNALD',
  'RUBEM',
  'SAMARA',
  'SIMONE',
  'TALITA',
  'THAYSLANE',
  'URBANIA',
  'VICTORIA',
  'VITORIA',
  'WENDEL'
];

export const MOTIVOS = [
  'ALHEIO À VONTADE (ÓBITO/JUDICIAL)',
  'ALTERAÇÃO DE COBERTURA/BENEFÍCIOS',
  'DESISTÊNCIA / MOTIVO PESSOAL',
  'FINANCEIRO',
  'INSATISFAÇÃO COM A ASSOCIAÇÃO',
  'INSATISFAÇÃO COM ASSISTÊNCIA 24H',
  'MUDANÇA DE ESTADO / PAÍS',
  'MUDANÇA PARA OUTRA ASSOCIAÇÃO/SEGURADORA',
  'MUDANÇA DE TITULARIDADE / TRANSFERÊNCIA',
  'OUTROS',
  'SINISTRO / VEÍCULO EM REPARO',
  'SUBSTITUIÇÃO DE VEÍCULO',
  'VEÍCULO PARADO / SEM USO',
  'VENDA DO VEÍCULO'
];

export const TIPO_VEICULO = [
  'AUTOMÓVEL',
  'CAMINHÃO',
  'CARRETA',
  'CONJUNTO'
];

export const RASTREADOR = [
  'TOP',
  'ROTA',
  'OUTROS',
  'NÃO',
];

export const ASSOCIACAO = [
  'APROVAUTO',
  'CONEXAO',
];

export const STATUS = [
  'Pendente',
  'Inativo',
];

export const BOLETO = [
  'Pago',
  'Aberto',
];

export const SOLICITACAO = [
  'Associado',
  'Consultor',
];
